# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff2cd64156e9c4ea3043fde85af784b12dceb1cfafdc6e7fee37842fe81466e254d3ac862510216fbddc6445ce04a879a2be999b6cb33f37a86ff637aebb226e

test:
  secret_key_base: bc860724c3de577d3b53f571d51429686cde2b722b8c7621872f066fa98c1019896a3c4c84e4152db5d3a988d69b847e725a3a4aa73c596bf671f2b0a56c719a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
